repos:
  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 3.4.2
    hooks:
      - id: sqlfluff-lint
        additional_dependencies: ["dbt-snowflake==1.10.0", "sqlfluff-templater-dbt==3.4.2"]
        types: [sql]
        exclude: "^target/"
        args: [--config, ".sqlfluff",
          --processes, "10"]
