name: dbt_service
version: "1.0"
config-version: 2

profile: default

model-paths: ["models"]
macro-paths: ["macros"]
seed-paths: ["seeds"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
log-path: "logs"

models:
  dbt_service:
    raw:
      +materialized: table
      +schema: RAW
    stg:
      +materialized: table
      +schema: STG
    mart:
      +materialized: view
      +schema: MART
