default:
  outputs:
    dev:
      account: "{{ secrets.SNOWFLAKE_ACCOUNT }}"
      database: "{{ secrets.SNOWFLAKE_DB }}"
      schema: "{{ secrets.SNOWFLAKE_SCHEMA }}"
      password: "{{ secrets.SNOWFLAKE_PASSWORD }}"
      role: "{{ secrets.SNOWFLAKE_ROLE }}"
      threads: 4
      type: snowflake
      user: "{{ secrets.SNOWFLAKE_USER }}"
      warehouse: COMPUTE_WH
  target: dev